### ISSUE TITLE
get the element where i opened the context menu

### ISSUE THREAD

**Issue by Impre-visible** [AnonymousXC/ContextMenu.js#1]
Hi, I want to use this context menu, but in my work I have to interact with the object where I clicked, is it possible to implement that pls ?

**Comment by AnonymousXC** [comment]
Working on it.

**Comment by AnonymousXC** [comment]
Yes.

You can use this in your code.

```Javascript
document.body.addEventListener("contextmenu", (e) => {
        console.log(e.target);
})
```


The `e.target` gives the element on which the context menu is opened.
